version: 0
allowPullRequests: public
tasks:
  - provisionerId: '{{ taskcluster.docker.provisionerId }}'
    workerType: '{{ taskcluster.docker.workerType }}'
    extra:
      github:
        events:
          - pull_request.opened
          - pull_request.reopened
          - push
          - pull_request.synchronize
    payload:
      maxRunTime: 3600
      image: djmitche/rust-hawk-test:3.0.0@sha256:f7ada4debbf1b6c0dbbb5f5c27783ebdf7660d7714378e78478d27e0489f300e
      command:
        - /bin/bash
        - '-c'
        - >-
          git clone {{event.head.repo.url}} repo &&
          cd repo &&
          git config advice.detachedHead false &&
          git checkout {{event.head.sha}} &&
          echo $PATH &&
          rustup run stable cargo test &&
          rustup run nightly cargo test &&
          rustup run nightly cargo clippy -- -D clippy
    metadata:
      name: Tests
      description: Run `cargo test`
      owner: '{{ event.head.user.email }}'
      source: '{{ event.head.repo.url }}'

