version: 1
policy:
  pullRequests: public
tasks:
  $if: 'tasks_for in ["github-push", "github-pull-request"]'
  then:
    $let:
      run:
        $if: 'tasks_for == "github-push"'
        then: true
        else: {$eval: 'event.action in ["opened", "reopened", "synchronize"]'}
      repo_url:
        $if: 'tasks_for == "github-push"'
        then: ${event.repository.clone_url}
        else: ${event.pull_request.head.repo.clone_url}
      ref:
        $if: 'tasks_for == "github-push"'
        then: ${event.after}
        else: ${event.pull_request.head.sha}
    in:
    - $if: run
      then:
        provisionerId: 'proj-taskcluster'
        workerType: 'ci'
        deadline: {$fromNow: '1 hour'}
        expires: {$fromNow: '1 day'}
        payload:
          maxRunTime: 3600
          image: djmitche/rust-hawk-test:1.61.0@sha256:aa17430b879705e4bb4771c79a70dffb7864a125920bcb7939909e20d6acd0ae
          command:
            - /bin/bash
            - '-c'
            - >-
              git clone ${repo_url} repo &&
              cd repo &&
              git config advice.detachedHead false &&
              git checkout ${ref} &&
              cargo test --features="use_ring" --no-default-features &&
              cargo test --features="use_openssl" --no-default-features &&
              cargo fmt -- --check &&
              cargo clippy
        metadata:
          name: Tests
          description: Run tests
          owner: nobody@mozilla.com
          source: ${repo_url}
